### PR TITLE
Labor Admin Overload Visibility #issue306

### PR DESCRIPTION
**Pull request by bryantal**
Issue: https://bitbucket.org/laborstudents/lsf-flask/issues/306/306-labor-admin-overload-visibility

Admin can now view overload forms that have been submitted by supervisors but not yet approved by students.

 

To test:

Create an overload form and check on pending form

### CODE REVIEW

**Comment by bryantal** [comment]
From @hmanalai: We don’t normally show the Approve column in the Pending Overload Forms tab (which is why we have the manage modal), but it is showing here and it has Pre-Student Approval status there, which kinda confused me at first. 
Since the manage modal tells the admin that the student hasn’t approved the form yet, I think we can get rid of the Approve column. 
But if we do want to keep a status on the table, then maybe we should change the name of the column to Status.
image

**Comment by bryantal** [comment]
> From @hmanalai: We don’t normally show the Approve column in the Pending Overload Forms tab (which is why we have the manage modal), but it is showing here and it has Pre-Student Approval status there, which kinda confused me at first. Since the manage modal tells the admin that the student hasn’t approved the form yet, I think we can get rid of the Approve column. But if we do want to keep a status on the table, then maybe we should change the name of the column to Status. image

From @MayJue: we thought that would just be a easy way for the admin to see which form is pre-approved and which is already approved by students. that way they can sort it and not have to click on each form just to see which is pre approved and which is approved if they are just trying to approve all the overload forms and not worrying about the pre-approved

**Comment by bryantal** [comment]
> > From @hmanalai: We don’t normally show the Approve column in the Pending Overload Forms tab (which is why we have the manage modal), but it is showing here and it has Pre-Student Approval status there, which kinda confused me at first. Since the manage modal tells the admin that the student hasn’t approved the form yet, I think we can get rid of the Approve column. But if we do want to keep a status on the table, then maybe we should change the name of the column to Status. image
> 
> From @MayJue: we thought that would just be a easy way for the admin to see which form is pre-approved and which is already approved by students. that way they can sort it and not have to click on each form just to see which is pre approved and which is approved if they are just trying to approve all the overload forms and not worrying about the pre-approved

From @hmanalai: Yes, I think adding the status would be helpful. But maybe we should also change the name of the column to match its data. You can also ask others what they think.

**Comment by bryantal** [comment]
> > From @hmanalai: We don’t normally show the Approve column in the Pending Overload Forms tab (which is why we have the manage modal), but it is showing here and it has Pre-Student Approval status there, which kinda confused me at first. Since the manage modal tells the admin that the student hasn’t approved the form yet, I think we can get rid of the Approve column. But if we do want to keep a status on the table, then maybe we should change the name of the column to Status. image
> 
> From @MayJue: we thought that would just be a easy way for the admin to see which form is pre-approved and which is already approved by students. that way they can sort it and not have to click on each form just to see which is pre approved and which is approved if they are just trying to approve all the overload forms and not worrying about the pre-approved

From @MayJue: However, if having that approve column is more confusing then helpful, then we just just easily remove it

**Comment by bryantal** [comment]
> > > From @hmanalai: We don’t normally show the Approve column in the Pending Overload Forms tab (which is why we have the manage modal), but it is showing here and it has Pre-Student Approval status there, which kinda confused me at first. Since the manage modal tells the admin that the student hasn’t approved the form yet, I think we can get rid of the Approve column. But if we do want to keep a status on the table, then maybe we should change the name of the column to Status. image
> > 
> > 
> > From @MayJue: we thought that would just be a easy way for the admin to see which form is pre-approved and which is already approved by students. that way they can sort it and not have to click on each form just to see which is pre approved and which is approved if they are just trying to approve all the overload forms and not worrying about the pre-approved
> 
> From @MayJue: However, if having that approve column is more confusing then helpful, then we just just easily remove it

From @hmanalai: You’re right. Maybe try asking in Slack channel what others think.

**Comment by bryantal** [comment]
> > From @hmanalai: We don’t normally show the Approve column in the Pending Overload Forms tab (which is why we have the manage modal), but it is showing here and it has Pre-Student Approval status there, which kinda confused me at first. Since the manage modal tells the admin that the student hasn’t approved the form yet, I think we can get rid of the Approve column. But if we do want to keep a status on the table, then maybe we should change the name of the column to Status. image
> 
> From @MayJue: we thought that would just be a easy way for the admin to see which form is pre-approved and which is already approved by students. that way they can sort it and not have to click on each form just to see which is pre approved and which is approved if they are just trying to approve all the overload forms and not worrying about the pre-approved

From @hmanalai: Did we decide to keep the Approve header? If so, I will approve the PR. Everything else looks good.

**Comment by bryantal** [comment]
> > > From @hmanalai: We don’t normally show the Approve column in the Pending Overload Forms tab (which is why we have the manage modal), but it is showing here and it has Pre-Student Approval status there, which kinda confused me at first. Since the manage modal tells the admin that the student hasn’t approved the form yet, I think we can get rid of the Approve column. But if we do want to keep a status on the table, then maybe we should change the name of the column to Status. image
> > 
> > 
> > From @MayJue: we thought that would just be a easy way for the admin to see which form is pre-approved and which is already approved by students. that way they can sort it and not have to click on each form just to see which is pre approved and which is approved if they are just trying to approve all the overload forms and not worrying about the pre-approved
> 
> From @hmanalai: Did we decide to keep the Approve header? If so, I will approve the PR. Everything else looks good.

From @MayJue: We changed the approve header to status and everything all issues in this branch has been addressed

**Comment by bryantal** [comment]
From @hmanalai: The counter in Pending Adjustment Forms doesn’t seem to update. Although there is a form in there, the counter is still zero. I checked this in the development branch and it was working fine, so you might wanna double-check this.
image

**Comment by Boorclark** [comment]
image
The counter seems to be working in this branch. Requesting review.

**Review by BrianRamsay — APPROVED** [review]

**Pull request merged**
