### PR TITLE
changed charfield to textfield and removed character limits

### PR DESCRIPTION
**Pull request by gahimbaref**
#392 
- Changed charfield to textfield for notes model
- Removed placeholder and character limit

Test:
- Go to pending forms under administration, click "actions" and view notes
- You should be able to add notes without limits
- There should be no placeholder

### CODE REVIEW

**Comment by Karina-Agliullova** [comment]
When I save a note that is too long, and then I click on 'actions' and view the notes, it goes over the borders
Screenshot (1291)

**Comment by Karina-Agliullova** [comment]
Also, I think having a slightly bigger area for text in notes would be helpful because it seems to be more user-friendly

**Comment by sreynit02** [comment]
> When I save a note that is too long, and then I click on 'actions' and view the notes, it goes over the borders Screenshot (1291)

This was an issue from before. It happens because the word is too long. Normally, we would not have a word that is that long make this error. We consulted Anderson and he said it is ok.

**Comment by sreynit02** [comment]
> Also, I think having a slightly bigger area for text in notes would be helpful because it seems to be more user-friendly

I think the size of the textbox is ok since it is located on a modal which is already small. We would have to make the modal bigger if we want a bigger textbox or take over space that could be the note log. Plus the notes are generally short.

**Review by AndersonStettner — CHANGES_REQUESTED** [review]
nevermind

**Comment by AndersonStettner** [comment]
> > Also, I think having a slightly bigger area for text in notes would be helpful because it seems to be more user-friendly
> 
> I think the size of the textbox is ok since it is located on a modal which is already small. We would have to make the modal bigger if we want a bigger textbox or take over space that could be the note log. Plus the notes are generally short.

If you increase the amount of rows when you create the textarea it will increase the height of the textarea and the modal will adjust itself to the size of the textarea by default.

**Comment by AndersonStettner** [comment]
> When I save a note that is too long, and then I click on 'actions' and view the notes, it goes over the borders Screenshot (1291)

If you give the div around the note these styles, it will keep super-long words from going outside of the box.
```
    text-overflow: ellipsis;
    white-space: nowrap;
    width: 100%;
    overflow: hidden;
```

**Comment by solijonovam** [comment]
looks all good! @Andersonstettner

**Review by AndersonStettner — APPROVED** [review]

**Pull request merged**
